apiVersion: v1
kind: Service
metadata:
  name: http-server-service
  namespace: http-server
spec:
  selector:
    app: http-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 83       
      targetPort: 80 